# Generated by Django 5.2.3 on 2025-06-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EXC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BTC', models.IntegerField(default=107754)),
                ('ETH', models.IntegerField(default=2485)),
                ('USDT', models.IntegerField(default=1.0002)),
                ('XPR', models.IntegerField(default=2.1885)),
                ('SOL', models.IntegerField(default=150)),
            ],
        ),
    ]
