# Generated by Django 5.2.3 on 2025-07-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EXC', '0002_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='addr',
            field=models.IntegerField(default=0, max_length=150, unique=True),
        ),
    ]
