# Generated by Django 5.2.3 on 2025-07-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EXC', '0003_userwallet_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='addr',
            field=models.IntegerField(max_length=150, unique=True),
        ),
    ]
