# Generated by Django 5.2.3 on 2025-07-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EXC', '0005_alter_userwallet_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='addr',
            field=models.IntegerField(),
        ),
    ]
